@startuml
interface "DNode<Survey> " as SurveyTree {
  +name: string
  +config: SurveyOptions
}

interface "DNode<Page> " as PageNode {
  +name: string | Record<string, string>
}

interface "DNode<PageItem> " as PageItemNode {
  +wording: string | Record<string, string>
  +varname: string
  +type: PageItemType
}

interface "DNode<PageSet> " as PageSetNode {
  +type: string | Record<string, string>
  +names: string[]
}

SurveyTree *--> "n" PageSetNode
SurveyTree *--> "n" PageNode
PageNode *--> "n" PageItemNode

hide methods

@enduml